HCS(1) - CMD line tool to control Voltcraft PPS and EA-PS series Power Supply
=============================================================================
:Author:                Qball Cow
:email:                 qball@gmpclient.org
:License: 				GPL-v2
:Source:				http://github.com/DaveDavenport/IfThenElse/
:home:                  /main.html
:toc:


Name
----

hcs - Small command-line tool to control a Voltcraft PPS-11360 Programmable DC Power Supply.

Synopsys
--------

hcs ['command']

DESCRIPTION
-----------

This manual page explains the *hcs* program. The *hcs* program provides basic control for the
Programmable DC Power Supply.

The tool allows you to retrieve status from the power supply, set voltage, current and output state.

COMMANDS
--------
Multiple commands can be specified in one go.

 * *auto*
Auto connect to first detected power supply.

 * *auto <id>*
Auto connect to detected power supply with <id>.

 * *list*
List autodetected power supplies.

 * *status*
Report status from the power supply. (Current voltage, current and active limiter)

 * *voltage*
Read the output voltage.

 * *voltage <value>*:
Set the output voltage (in Volts).

 * *current*
Read the output current limit.

 * *current <value>*:
Set the output current limiter (in Amps).

 * *off*
Turn the output off.

 * *on*
Turn the output on.

 * *interactive*
Go into interactive mode.

EXAMPLES
--------

   hcs voltage 5 output 1.3 status

Set the output voltage to 5Volts, the output current limit to 1.3Amps and report the current status.

   ---------------------------------------

    Device information:
     Device Type:               PS 2042-06B
     Manufacturer:                       EA
     Article No. :                 39------
     Serial Num.:                269-------
     Software Version:     V4.02 05.12.2012

    Device specifications:
     Nominal voltage:                 42.00
     Nominal current:                  6.00
     Nominal power:                  100.00
     Set OVP:                         46.20
     Set OCP:                          6.60
     Set voltage:                      5.00
     Set current:                      0.50
     Current voltage:                  0.00
     Current current:                  0.00
     Current power:                    0.00
     Current mode:                      Off

See status of EA-PS 2042-06 B power supply. 

ENVIRONMENT VARIABLES
---------------------

hcs obeys the following environment variables:

* *HCS_DEVICE*
The device node pointing to the serial device of the programmable power supply.

'Default:'

 /dev/ttyUSB0


SUPPORTED DEVICES
-----------------

The following device(s) are known to work:

 * Voltcraft PPS-11360
 * Elektro-Automatik EA-PS 2000 series.
    - Tested with EA-PS 2042-06 B


BUGS
----

Please report bugs on the GITHUB issues page: https://github.com/DaveDavenport/hcs

LICENSE
-------

This program is licensed under GPL 2.0.
